stages:
  - install
  - lint
  - test
  - build

  variables:
    TEST_DATABASE: "mongodb+srv://munirkhaliqyar:2vmJgN0QHO0wDFfJ@cluster0.k5q7web.mongodb.net/test"

cache:
  paths:
    - node_modules/

install-job:
  stage: install
  script:
    - npm ci
    - cd client && npm ci
    - npm install eslint@latest
    - npm install eslint-plugin-react@latest --save-dev

#lint-job:
  # stage: lint
  # script:
  #   - echo "Linting..."
  #   - npm run lint
  # artifacts:
  #   name: "lint"
  #   paths:
  #     - lintArtifiacts/
  #   untracked: true
  #   when: on_success

test-job:
  stage: test
  script:
    - echo "Testing..."
    - npm ci --production=false
    - npm run test
  artifacts:
    name: "test"
    paths:
      - testArtifacts/
    untracked: true
    when: on_success

build-job:
  stage: build
  script: 
    - echo "Building..."
    - npm run build
    - npm run bundle
  artifacts:
    name: "build"
    paths:
    - dist/bundle.zip
    untracked: true