stages:
  - install
  - lint
  - document
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - client/node_modules/

install-job:
  stage: install
  script:
    - npm ci
    - cd ./client
    - npm ci

lint-job:
  stage: lint
  script:
    - echo "Linting..."
    - npm run lint
  artifacts:
    name: "lint"
    paths:
      - ./lintArtifact/eslint-report.html
    exclude:
      - node_modules/*
      - client/node_modules/*
    untracked: true
    when: on_success

doc-job:
  stage: document
  script:
    - echo "Documenting..."
    - npm run doc
  artifacts:
    name: "documentation"
    paths:
      - ./docs/*
    exclude:
      - node_modules/*
      - client/node_modules/*
    untracked: true
    when: on_success

build-job:
  stage: build
  script: 
    - echo "Building..."
    - npm run build
    - npm run bundle
  artifacts:
    name: "build"
    paths:
      - ./*
    exclude:
      - node_modules/*
      - client/node_modules/*
    untracked: true
  when: on_success

deploy-job:
  stage: deploy
  script: 
    - echo "Deploying..."
    - npm run deploy
  